apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: default
spec:
  # ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: busybox:1.35
        command:
          - sh
          - -c
          - echo "starting db migration"
